[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "ftests"
script = "fscripts"
optimizer = true
optimizer_runs = 200
solc = "0.8.27"
evm_version = "shanghai"
remappings = [
  "@openzeppelin/contracts=lib/OpenZeppelin/openzeppelin-contracts@4.9.0/contracts",
  "@openzeppelin/contracts-upgradeable=lib/OpenZeppelin/openzeppelin-contracts-upgradeable@4.9.0/contracts",
  "@openzeppelin-upgrades=lib/OpenZeppelin/openzeppelin-contracts-upgradeable@4.9.0",
  "solidity-bytes-utils/contracts=lib/GNSPS/solidity-bytes-utils@0.8.0/contracts",
  "@eigenlayer/contracts=lib/eigenlayer-contracts/eigenlayer-contracts@1.6.0/src/contracts",
  "interfaces=./interfaces",
]
