[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "ftests"
script = "fscripts"
optimizer = true
optimizer_runs = 200
solc = "0.8.17"
evm_version = "prague"
remappings = [
  "interfaces=contracts/interfaces",
  "@eigenlayer/contracts=lib/eigenlayer-contracts-0.4.3-mainnet-rewards-foundation-incentives/src/contracts",
  "@openzeppelin/contracts=lib/OpenZeppelin/openzeppelin-contracts@4.4.2/contracts",
  "@openzeppelin/contracts-upgradeable=lib/OpenZeppelin/openzeppelin-contracts-upgradeable@4.6.0/contracts",
  "solidity-bytes-utils/contracts=lib/GNSPS/solidity-bytes-utils@0.8.0/contracts",
]

[rpc_endpoints]
local = "http://localhost:8545"
